---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
library(dplyr)
library(ggplot2)
library(knitr)
if (!file.exists("activity.csv"))  {
    dataset_url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
    download.file(dataset_url, "activity.zip")
    unzip("activity.zip")
    file.remove("activity.zip")
}
data <- read.csv("activity.csv")
```


## What is mean total number of steps taken per day?
```{r}
dataByDate <- group_by(na.omit(data),date)
totalStepsInDay <- summarize(dataByDate, total = sum(steps))
hist(totalStepsInDay$total,xlab="Total number of steps each day",main="Histogram of total number of steps each day")
mean(totalStepsInDay$total)
median(totalStepsInDay$total)
```


## What is the average daily activity pattern?
```{r}
stepsInInterval <- aggregate(steps ~ interval, data, mean)
plot(stepsInInterval$interval, stepsInInterval$steps, type='l',main="Average number of steps taken across all days",xlab="Interval",ylab="Average number of steps")
stepsInInterval[which.max(stepsInInterval$steps),]
```

## Inputing missing values
```{r}
length(which(is.na(data$steps)))
## In the code below, NA have been replaced with mean for that 5-minute interval.
modifiedData <- data
for (i in 1:nrow(modifiedData))  {
    if (is.na(modifiedData$steps[i]))  {
        intervalValue <- modifiedData$interval[i]
        stepsValue <- stepsInInterval[stepsInInterval$interval == intervalValue,]
        modifiedData$steps[i] <- stepsValue$steps
    }
}
modifiedDataDbD <- aggregate(steps ~ date, modifiedData, sum)
head(modifiedDataDbD)
hist(modifiedDataDbD$steps, main = "Histogram of total steps per day (modified", xlab = "Total number of steps in a day")
mean(modifiedDataDbD$steps)
median(modifiedDataDbD$steps)
mean(totalStepsInDay$total)
median(totalStepsInDay$total)
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
modifiedData['typeOfDay'] <- weekdays(as.Date(modifiedData$date))
modifiedData$typeOfDay[modifiedData$typeOfDay  %in% c('Saturday','Sunday') ] <- "weekend"
modifiedData$typeOfDay[modifiedData$typeOfDay != "weekend"] <- "weekday"

modifiedData$typeOfDay <- as.factor(modifiedData$typeOfDay)
modifiedDataStepsByInterval <- aggregate(steps ~ interval + typeOfDay, modifiedData, mean)

# plot
qplot(interval, 
      steps, 
      data = modifiedDataStepsByInterval, 
      type = 'l', 
      geom=c("line"),
      xlab = "Interval", 
      ylab = "Number of steps", 
      main = "") +
  facet_wrap(~ typeOfDay, ncol = 1)
```
